// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"fmt"
	"github.com/google/wire"
	"go.kirha.ai/kirha-mcp-gateway/internal/adapters/clients/kirha"
	"go.kirha.ai/kirha-mcp-gateway/internal/adapters/handlers/mcp"
	"go.kirha.ai/kirha-mcp-gateway/internal/applications/toolapp"
	"go.kirha.ai/kirha-mcp-gateway/internal/core/ports/clients"
	"go.kirha.ai/mcpmux"
	"os"
)

// Injectors from wire.go:

func ProvideKirhaClient() (clients.KirhaClient, error) {
	config, err := kirha.LoadConfig()
	if err != nil {
		return nil, err
	}
	kirhaClient := kirha.New(config)
	return kirhaClient, nil
}

func ProvideHTTPServer() (*mcp.Server, error) {
	kirhaClient, err := ProvideKirhaClient()
	if err != nil {
		return nil, err
	}
	application := ProvideToolApplication(kirhaClient)
	httpConfig, err := ProvideHTTPConfig()
	if err != nil {
		return nil, err
	}
	transport := ProvideHTTPTransport(httpConfig)
	server := mcp.New(application, transport)
	return server, nil
}

func ProvideStdioServer() (*mcp.Server, error) {
	kirhaClient, err := ProvideKirhaClient()
	if err != nil {
		return nil, err
	}
	application := ProvideToolApplication(kirhaClient)
	transport := ProvideStdioTransport()
	server := mcp.New(application, transport)
	return server, nil
}

// wire.go:

func ProvideToolApplication(k clients.KirhaClient) *toolapp.Application {
	return toolapp.New(k)
}

func ProvideStdioTransport() mcpmux.Transport {
	return mcpmux.NewStdioTransport(&mcpmux.StdioTransportConfig{
		Stdin:  os.Stdin,
		Stdout: os.Stdout,
		Stderr: os.Stderr,
	})
}

func ProvideHTTPConfig() (*mcp.HTTPConfig, error) {
	return mcp.LoadHTTPConfig()
}

func ProvideHTTPTransport(cfg *mcp.HTTPConfig) mcpmux.Transport {
	return mcpmux.NewHTTPTransport(&mcpmux.HTTPTransportConfig{
		Addr:            fmt.Sprintf(":%d", cfg.Port),
		Path:            "/mcp",
		AllowedOrigins:  []string{"*"},
		ResponseTimeout: cfg.ToolTimeout,
	})
}

var applicationSet = wire.NewSet(
	ProvideKirhaClient,
	ProvideToolApplication,
)

var httpSet = wire.NewSet(
	applicationSet,
	ProvideHTTPConfig,
	ProvideHTTPTransport,
)

var stdioSet = wire.NewSet(
	applicationSet,
	ProvideStdioTransport,
)
