name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-dxt:
    name: Build and upload DXT pack
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install DXT CLI
        run: npm install -g @anthropic-ai/dxt

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Build DXT pack
        run: dxt pack

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kirha-mcp-gateway.dxt
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  push_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            kirhaai/kirha-mcp-gateway:latest
            kirhaai/kirha-mcp-gateway:${{ github.event.release.tag_name }}