name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-dxt:
    name: Build and upload DXT pack
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install DXT CLI
        run: npm install -g @anthropic-ai/dxt

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Build DXT pack
        run: dxt pack

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kirha-mcp-gateway.dxt
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
